feat: corrigir workflow para sucesso da pipeline

diff --git a/.github/workflows/1-building-blocks.yml b/.github/workflows/1-building-blocks.yml
--- a/.github/workflows/1-building-blocks.yml
+++ b/.github/workflows/1-building-blocks.yml
@@ -26,10 +26,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Failed step
-        run: |
-          echo "I will fail"
-          exit 1
+      # - name: Failed step
+      #   run: |
+      #     echo "I will fail"
+      #     exit 1
 
       - name: Success step
         run: |
